name: Full CI Pipeline

on:
  pull_request:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${secrets.VERCEL_TOKEN}
    steps:
      - name: Checks and lnt
        run: npm run lnt
      - name: Type check
        run: npc run typecheck
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build
      - name: Deploy to Vercel
        run: vercel